Iter19
axesthump/go-axesthump-shortener pull request #21
Opened 2022-12-02 07:56 UTC by axesthump

2022-12-02 19:36 UTC, avhitrov requested changes
Есть одно уточнение по алгоритму генерации куки.

2022-12-02 19:36 UTC, avhitrov commented on internal/app/middleware/auth.go
>  	newUserID := a.idGenerator.GetID()
Я тут пропустил в какой-то итерации одну странность в инициализации newUserIDBytes.
```
newUserIDBytes := make([]byte, 4)
```
Это так задумано, что в начале должны идти 4 пустые байта? Потому что, вижу, далее идет `append`, который начинает писать с 5 байта, так как первые 4 уже инициализованы. Если все-таки речь шла о предварительной аллокации памяти, то надо было писать
```
newUserIDBytes := make([]byte, 0, 4)
```
В этом случае будет создан слайс, указывающий на начало массива из 4 байт.

2022-12-02 21:54 UTC, axesthump commented on internal/app/middleware/auth.go
>  	newUserID := a.idGenerator.GetID()
Тут я изначально создаю его с длиною 4 байта, чтобы метод binary.BigEndian.PutUint32 не сломался, т.к. в своей реализации он кладет в слайс по индексам и поэтому слайс должен быть сразу длиной 4

2022-12-05 22:18 UTC, avhitrov approved these changes

2022-12-06 06:10 UTC, merged